name: Musl Toolchain
description: Install Elide's musl toolchain in GHA

inputs:
  revision:
    description: Revision
  version:
    description: Version
    default: "1.2.51"
  baseline:
    description: Baseline
    default: "1.2.5"
  arch:
    description: Architecture
    required: false
    default: amd64

outputs:
  musl-home:
    description: Path to the installed toolchain

runs:
  using: node24
  main: dist/main.js
