BUILD_ZLIB=yes
BUILD_ZLIB_NG=yes
BUILD_BROTLI=yes
BUILD_SNAPPY=yes
BUILD_ZSTD=yes
BUILD_OPENSSL=yes
BUILD_LLVM=yes
BUILD_SQLITE=yes
BUILD_SQLCIPHER=yes
BUILD_CAPNP=no
BUILD_STAGE2=yes

RELEASE=yes
HARDEN=yes
SECURE=OFF
GUARDED=OFF
CFI=no
MPK=no
LLVM_PROJECTS="clang;lld"

USE_MUSL_CROSSMAKE=yes
USE_SCCACHE=yes
USE_WIDE_VECTORS=no
CLEAN_BEFORE_BUILD=yes
MUSL_USE_MIMALLOC=no
MAKE_SYMLINK=no

MODERN_X86_64_ARCH_TARGET=x86-64-v4
MODERN_X86_64_ARCH_TUNE=znver3
MODERN_AARCH64_ARCH_TARGET=armv8.2-a+crypto+crc
MODERN_AARCH64_ARCH_TUNE=generic
