BUILD_BROTLI=no
BUILD_CAPNP=no
BUILD_CRC32C=no
BUILD_HIREDIS=no
BUILD_LEVELDB=no
BUILD_LLVM=no
BUILD_OPENSSL=no
BUILD_SNAPPY=no
BUILD_SQLCIPHER=no
BUILD_SQLITE=no
BUILD_STAGE2=no
BUILD_ZLIB_NG=no
BUILD_ZLIB=no
BUILD_ZSTD=no
BUILD_LZ4=no

RELEASE=yes
HARDEN=yes
SECURE=OFF
GUARDED=OFF
CFI=no
MPK=no
LLVM_PROJECTS="clang;lld"

USE_MUSL_CROSSMAKE=yes
USE_SCCACHE=yes
USE_WIDE_VECTORS=no
CLEAN_BEFORE_BUILD=yes
MUSL_USE_MIMALLOC=no
MAKE_SYMLINK=no

MODERN_X86_64_ARCH_TARGET=x86-64-v4
MODERN_X86_64_ARCH_TUNE=znver3
MODERN_AARCH64_ARCH_TARGET=armv8.2-a+crypto+crc
MODERN_AARCH64_ARCH_TUNE=generic
